version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.50.0
    ports:
      - "9090:9090"
    configs:
      - source: prom_config
        target: /etc/prometheus/prometheus.yml
    networks:
      - web
    deploy:
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana:10.4.0
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - web
    deploy:
      placement:
        constraints:
          - node.role == manager

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - web
    deploy:
      mode: global

  node-exporter:
    image: prom/node-exporter
    networks:
      - web
    deploy:
      mode: global

configs:
  prom_config:
    file: ./prometheus.yml

volumes:
  grafana_data:

networks:
  web:
    external: true
